# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
import numpy as np

arr = np.random.randint(1,21, size= (6,6))
print(arr)

arr[:,2]= 1
print("modified array: ")
print(arr)


[[18 14 20 19 13 10]
 [ 4 16  8  3  1  7]
 [10  7 20  6  3  2]
 [ 4  8 10  4  4  4]
 [19 11  8  7  4  4]
 [ 5 18  3 14  3 18]]
modified array: 
[[18 14  1 19 13 10]
 [ 4 16  1  3  1  7]
 [10  7  1  6  3  2]
 [ 4  8  1  4  4  4]
 [19 11  1  7  4  4]
 [ 5 18  1 14  3 18]]


In [5]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr = np.random.randint(1,17, size= (5,5))
print(arr)

np. fill_diagonal(arr,0)
print("modified array: ")
print(arr)

[[ 6 16  2 10 16]
 [ 7 10 12  3 15]
 [ 1  3  4  6  1]
 [11 10 15  1 10]
 [ 6  5 13  7 10]]
modified array: 
[[ 0 16  2 10 16]
 [ 7  0 12  3 15]
 [ 1  3  0  6  1]
 [11 10 15  0 10]
 [ 6  5 13  7  0]]


In [4]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

import numpy as np  
arr= np.random.randint(1,37, size=(6,6))
print(arr)
sub_array= arr[2:5,1:4]
print("the subarray is : ")
print(sub_array)


[[ 3  6 16 32  2 31]
 [17 30 11 22  9 24]
 [ 6 12 35 17 26 10]
 [15 29 27 26  2 14]
 [31 19 26 10  2 27]
 [29 34 27 13  5  6]]
the subarray is : 
[[12 35 17]
 [29 27 26]
 [19 26 10]]


In [12]:
# Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
import numpy as np

# Create a 5x5 array with random integers
array = np.random.randint(0, 100, (5, 5))
print("Array:\n", array)

# Extract the border elements
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("\nBorder elements:\n", border_elements)



Array:
 [[99 72 74 14 32]
 [54 50 57 97 59]
 [ 7 74 34 12  3]
 [95 17 38 86  2]
 [72 32  0 10 23]]

Border elements:
 [99 72 74 14 32 72 32  0 10 23 54  7 95 59  3  2]


In [17]:
#  Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
arr1 = np.random.randint(1,11, size=(3,4))
arr2 = np.random.randint(1,11, size=(3,4))
print(f"the first array is: \n {arr1}\n")
print(f"the second array is: \n {arr2}\n")

addele = arr1 + arr2
subele = arr1 - arr2
mulele = arr1 * arr2
divele = arr1/arr2

print(f"the addtion of two arrays are:\n {addele}\n")
print(f"the subtraction of two arrays are:\n {subele}\n")
print(f"the multiplication of two arrays are:\n {mulele}\n")
print(f"the division of two arrays are:\n {divele}\n")

the first array is: 
 [[ 6  1  2  5]
 [ 1  7 10  3]
 [ 9  4  2  8]]

the second array is: 
 [[ 6 10  6  5]
 [ 8  6  6  9]
 [ 5  2  7  2]]

the addtion of two arrays are:
 [[12 11  8 10]
 [ 9 13 16 12]
 [14  6  9 10]]

the subtraction of two arrays are:
 [[ 0 -9 -4  0]
 [-7  1  4 -6]
 [ 4  2 -5  6]]

the multiplication of two arrays are:
 [[36 10 12 25]
 [ 8 42 60 27]
 [45  8 14 16]]

the division of two arrays are:
 [[1.         0.1        0.33333333 1.        ]
 [0.125      1.16666667 1.66666667 0.33333333]
 [1.8        2.         0.28571429 4.        ]]



In [20]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr = np.random.randint(1,11, size=(4,4))
print(f"the original array:\n{arr}\n")

row_sum= np.sum(arr, axis=1)
print(f"the row-wise sum of array is: \n{row_sum}\n")

col_sum= np.sum(arr, axis=0)
print(f"the col-wise sum of array is: \n{col_sum}\n")

the original array:
[[ 2  6  2 10]
 [ 6  4  8  3]
 [ 1  7  8  1]
 [ 2  6  3  6]]

the row-wise sum of array is: 
[20 21 17 17]

the col-wise sum of array is: 
[11 23 21 20]



In [22]:
# Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr= np.random.randint(1, 11, size=(5, 5))
print(f"the original array: \n{arr}\n")

mean= np.mean(arr)
median= np.median(arr)
std= np.std(arr)
var= np.var(arr)

print(f"the mean of above array is: {mean}\n")
print(f"the median of above array is: {median}\n")
print(f"the std of above array is: {std}\n")
print(f"the var of above array is: {var}\n")

the original array: 
[[ 7  1  2  2  6]
 [ 6  4  7  6  8]
 [ 1  4  1  4  1]
 [10  5  5 10  8]
 [ 2  8  9  6  3]]

the mean of above array is: 5.04

the median of above array is: 5.0

the std of above array is: 2.8492806109613005

the var of above array is: 8.118400000000001



In [25]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr= np.arange(1, 10).reshape(3,3)
print(f"the original array: \n{arr}\n")

mean= np.mean(arr)
std= np.std(arr)

normalized_array= (arr-mean)/std
print(f"normalized array is: \n {normalized_array}\n")



the original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

normalized array is: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]



In [26]:
# Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
org_arr= np.random.randint(1,11, size=(3,3))
row_arr= np.random.randint(1,11, size=(3,))
print(f"the original array given: \n{org_arr}\n")
print(f"the row array given: \n{row_arr}\n")

brod_arr= org_arr + row_arr

print(f"the brodcasted array is: \n{brod_arr}\n")

the original array given: 
[[ 3  1  8]
 [ 1  7  5]
 [ 1  1 10]]

the row array given: 
[3 1 3]

the brodcasted array is: 
[[ 6  2 11]
 [ 4  8  8]
 [ 4  2 13]]



In [28]:
# Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

org_arr= np.random.randint(1,11, size=(4,4))
sub_arr= np.random.randint(1,6, size=(4,))
print(f"the original array: \n{org_arr}\n")
print(f"the 1D array: \n{sub_arr}\n")

resulted_array= org_arr - sub_arr[:, np.newaxis]
print(f"the resulted array is: \n{resulted_array}\n")

the original array: 
[[7 8 1 3]
 [8 8 5 1]
 [7 9 2 2]
 [6 7 3 5]]

the 1D array: 
[4 2 5 1]

the resulted array is: 
[[ 3  4 -3 -1]
 [ 6  6  3 -1]
 [ 2  4 -3 -3]
 [ 5  6  2  4]]



In [31]:
# Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
matrix= np.random.randint(1,11, size=(3,3))
print(f"the matrix given:\n{matrix}\n")

determinant= np.linalg.det(matrix)
print(f"the determinant of the matrix is: {determinant}\n")
Inverse= np.linalg.inv(matrix)
print(f"the Inverse of the matrix is: \n{Inverse}\n")
Eigenvalues= np.linalg.eigvals(matrix)
print(f"the Eigenvalues of the matrix is: \n{Eigenvalues}\n")


the matrix given:
[[ 7  6  7]
 [ 1 10  1]
 [ 3  4  7]]

the determinant of the matrix is: 255.99999999999994

the Inverse of the matrix is: 
[[ 0.2578125 -0.0546875 -0.25     ]
 [-0.015625   0.109375   0.       ]
 [-0.1015625 -0.0390625  0.25     ]]

the Eigenvalues of the matrix is: 
[14.05335943  2.4203554   7.52628517]



In [32]:

# Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
array1= np.random.randint(1,11, size=(2,3))
array2= np.random.randint(1,11, size=(3,2))
print(f"the given array1 is: \n{array1}\n")
print(f"the given array2 is: \n{array2}\n")

array_multiplication= np.dot(array1,array2)
print(f"the multiplication of given two matrix is: \n{array_multiplication}")

the given array1 is: 
[[ 9 10  1]
 [ 2  8  6]]

the given array2 is: 
[[4 7]
 [8 4]
 [3 1]]

the multiplication of given two matrix is: 
[[119 104]
 [ 90  52]]


In [36]:

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
org_arr= np.arange(1,10).reshape(3,3)
print(f"the given original array is: \n{org_arr}\n")

reshaped_array= org_arr.reshape(1,9)
print(f"reshaped array to (1,9) looks like: \n{reshaped_array}\n")

reshaped_array= org_arr.reshape(9,1)
print(f"the reshaped array to (9,1) looks like: \n{reshaped_array}\n")


the given original array is: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

reshaped array to (1,9) looks like: 
[[1 2 3 4 5 6 7 8 9]]

the reshaped array to (9,1) looks like: 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]



In [4]:
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
import numpy as np
org_arr= np.random.randint(1,11, size=(5,5))
print(f"the original array: \n{org_arr}\n")

flatten_arr= org_arr.flatten()
print(f"the flatten array is : \n{flatten_arr}\n")

reshaped_array= flatten_arr.reshape(5,5)
print(f"the reshaped array looks like: \n{reshaped_array}\n")


the original array: 
[[ 6  2  5  4  7]
 [10  2  2  5 10]
 [ 8  1  8  1  4]
 [ 1  4  5  9  1]
 [ 2  8 10  1  3]]

the flatten array is : 
[ 6  2  5  4  7 10  2  2  5 10  8  1  8  1  4  1  4  5  9  1  2  8 10  1
  3]

the reshaped array looks like: 
[[ 6  2  5  4  7]
 [10  2  2  5 10]
 [ 8  1  8  1  4]
 [ 1  4  5  9  1]
 [ 2  8 10  1  3]]



In [9]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
org_arr= np.random.randint(1,11, size=(5,5))
print(f"the original array given: \n{org_arr}\n")

corners= org_arr[[0,0,-1,-1], [0,-1,0,-1]]
print(f"the corner elements are: \n{corners}\n")

the original array given: 
[[ 6 10  4  1  1]
 [10  8  3  2  9]
 [ 8  6  7  1  2]
 [ 1  6  8  3  5]
 [ 1  2  6  3 10]]

the corner elements are: 
[ 6  1  1 10]



In [ ]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.



In [ ]:
# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [ ]:
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.





In [ ]:
# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [ ]:
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
